### ISSUE TITLE
cannot run a single simulation 

### ISSUE THREAD

**Issue by tyhlee** [resplab/epicR#105]
Am I missing something? How do you use this package?
`
> library(epicR)
> init_session()
Initializing the session
[1] 0
> run(max_n_agents = 100000,input=init_input()$values)
[1] 0
> Cget_all_events()
data frame with 0 columns and 0 rows
> Cget_all_events_matrix()
     id local_time female time_at_creation age_at_creation pack_years gold event FEV1 FEV1_slope FEV1_acceleration pred_FEV1 smoking_status
     localtime_at_COPD age_at_COPD weight_at_COPD height followup_after_COPD FEV1_baseline exac_status cough phlegm wheeze dyspnea gpvisits
     diagnosis time_at_diagnosis medication_status case_detection cumul_cost cumul_qaly
> get_all_events()
Error in matrix(unlist(x), nrow = length(x), byrow = T) : 
  'data' must be of a vector type, was 'NULL'
> get_all_vars()
Error in terms.formula(formula, data = data) : 
  argument is not a valid model
> terminate_session()
Terminating the session
[1] 0
`

**Comment by aminadibi** [comment]
By default event matrix is not collected. For the quickest fix, clone the repo, turn on event mode in core.R and recompile locally.
