### ISSUE TITLE
Background mortality rates need to be calibrated for medication

### ISSUE THREAD

**Issue by safaahmadian** [resplab/epicR#111]

**Comment by aminadibi** [comment]
Following recalibration of exacerbations, in https://github.com/resplab/epicR/commit/95034304ef8a03c8264e530e27a33755c6e9e806, mortality looks like this: 
![image](https://user-images.githubusercontent.com/20497354/180888245-511294b7-f815-415b-a985-ce6c8a2f4f4a.png)

**Comment by aminadibi** [comment]
After recalibrating mortality in https://github.com/resplab/epicR/commit/3f2e210d0d587182e4b181fec0dcb46a4a3b010b we have:

![image](https://user-images.githubusercontent.com/20497354/180889105-a170f5cd-ebea-442d-acf6-b9456dea7358.png)
