### ISSUE TITLE
a small bug in outputs for diagnosed patients

### ISSUE THREAD

**Issue by safaahmadian** [resplab/epicR#115]
In **model.cpp > event_exacerbation_process**,  the section for # (OUTPUT_EX & OUTPUT_EX_EXACERBATION)>0 should be **moved to the end of the function**, after diagnosis_flag is updated.

**Comment by aminadibi** [comment]
Can you explain the rationale for why that should be the case? @safaahmadian

**Comment by safaahmadian** [comment]
Some outputs depend on the state of diagnosis. When a patient has an exacerbation, she might get diagnosed immediately. In that case, we should add to the number of exacerbations in diagnosed patients, rather than undiagnosed ones. I found the bug due to the inconsistency between the event_matrix and the output_ex, because the exacerbation_ event is pushed to the matrix after the diagnosis has been updated.
