### ISSUE TITLE
Add option to begin case detection after X years

### ISSUE THREAD

**Issue by rachaelmountain** [resplab/epicR#121]
I need to begin the budget impact analysis in 2021. Can the case detection module be "switched on" based on local time (e.g. using an if statement) so that we're still simulating the 2015-2020 period with no case detection?

Priority: medium

**Comment by aminadibi** [comment]
So, I attempted this by adding a `settings$record_from_year ` parameter and resetting `output()` and `output_ex()` in the annual event whenever `settings.record_from_year>floor((*ag).local_time)`. Turns out it's a bad idea and will cause an infinite loop, as epic uses n_base_agent in the output to end the run.

**Comment by aminadibi** [comment]
For some reason the same approach fails to reset `output_ex`. Strange

**Comment by aminadibi** [comment]
Resetting `output_ex` in event fixed works, but increases run time by a factor of 4!

**Comment by rachaelmountain** [comment]
Increases run time by a factor of 4 compared to storing all the years' data? Then I don't think it's entirely necessary to reset output_ex in the annual event. As long as we have the figures I need reported annually and we can control the case detection module through p_case_detection as a vector, what's the benefit of resetting output_ex?

**Comment by aminadibi** [comment]
I guess we can leave it as is then @KateJohnson  @rachaelmountain  Otherwise, there's currently no way to switch case detection on and off based on local time, since it's being applied at the input file level.

**Comment by aminadibi** [comment]
I guess we can leave it as is then @KateJohnson @rachaelmountain Otherwise, I've added vactorized case_detection probability. Please test and let me know if it works as expected.

**Comment by aminadibi** [comment]
Excellent
